
//vehicle
export const SET_PILOTS = 'SET_PILOTS';
export const SET_PLANETS = 'SET_PLANETS';
export const SET_SUM_MAP = 'SET_SUM_MAP';
export const SET_HIGHEST_POPULATION_VEHICLE = 'SET_HIGHEST_POPULATION_VEHICLE';
export const SET_PLANETS_LIST = 'SET_PLANETS_LIST';

export const FETCH_START = 'FETCH_START';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';

export const FETCH_PILOTS_SUCCESS = 'FETCH_PILOTS_SUCCESS';
export const FETCH_VEHICLES_SUCCESS = 'FETCH_VEHICLES_SUCCESS';
export const FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS';
